using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace EG
{
    public class Scene : AppMonoBehaviour
    {

        protected SceneManager m_SceneManager = null;
        protected ViewController m_ViewController = null;

        bool m_Activate = false;
        bool m_Startup = false;
        protected StateMachine m_State = new StateMachine();
        protected string m_StateNext = "";
        protected ViewBase m_RootView = null;
        protected CachePool m_CachePool = null;

        // 例外I理
        private bool m_BGMContinue = false;                    // シ`ンまたぎでBGMを停止するかどうか

        #endregion

        // プロパティ
        #region プロパティ

        new public string name { get { return ""; } }

        public ViewController ViewController { get { return m_ViewController; } }

        public StateMachine.State CurrentState { get { return m_State.GetCurrentState(); } }

        public CachePool CachePool { get { return m_CachePool; } }

        public bool BgmContinue
        {
            get { return m_BGMContinue; }
            set { m_BGMContinue = value; }
        }

        #endregion

        /// ***********************************************************************

        /// ***********************************************************************
        public static Scene Current()
        {
            return SceneManager.Current;
        }

        /// ***********************************************************************
        /// <summary>
        /// カレントシ`ンの取得
        /// </summary>
        /// ***********************************************************************
        public static T Current<T>() where T : Scene
        {
            return SceneManager.Current as T;
        }

        //=========================================================================
        //. コル`チン
        //=========================================================================
        #region コル`チン

        /// ***********************************************************************
        /// <summary>
        /// コル`チン_始
        /// </summary>
        /// ***********************************************************************
        public static Coroutine StartExecuter(IEnumerator routine)
        {
            Scene scene = Current();
            if (scene != null)
            {
                return scene.StartCoroutine(routine);
            }
            return null;
        }

        /// ***********************************************************************
        /// <summary>
        /// コル`チン_始
        /// </summary>
        /// ***********************************************************************
        public static Coroutine StartExecuter(IEnumerator routine, System.Action callback)
        {
            Scene scene = Current();
            if (scene != null)
            {
                return scene.StartCoroutine(WorkCoroutine(routine, callback));
            }
            return null;
        }
        // ワ`カ`コル`チン( K了rにコ`ルバックv数をg行する )
        private static IEnumerator WorkCoroutine(IEnumerator target, System.Action callback)
        {
            yield return target;
            callback();
        }

        /// ***********************************************************************
        /// <summary>
        /// コル`チン停止
        /// </summary>
        /// ***********************************************************************
        public static void StopExecuter(Coroutine coroutine)
        {
            Scene scene = Current();
            if (scene != null)
            {
                scene.StopCoroutine(coroutine);
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// コル`チン全停止
        /// </summary>
        /// ***********************************************************************
        public static void StopAllExecuter()
        {
            Scene scene = Current();
            if (scene != null)
            {
                scene.StopAllCoroutines();
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// ディレイエグゼキュ`タ`の_始
        /// </summary>
        /// ***********************************************************************
        public static Coroutine StartDelayExecuter(float delay, System.Action<object> action, object value = null)
        {
            Scene scene = Current();
            if (scene != null)
            {
                return scene.StartCoroutine(DelayExecuter(delay, action, value));
            }
            return null;
        }
        public static IEnumerator DelayExecuter(float delay, System.Action<object> action, object value)
        {
            while (delay > 0)
            {
                delay -= TimerManager.DeltaTime;
                yield return null;
            }
            if (action != null) action.Invoke(value);
        }

        #endregion

        //=========================================================================
        //. キャッシュ
        //=========================================================================
        #region キャッシュ

        /// ***********************************************************************
        /// <summary>
        /// キャッシュの追加
        /// </summary>
        /// ***********************************************************************
        public static void AddCache(GameObject gobj)
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.AddCache(gobj);
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 指定キ`のキャッシュを全破
        /// </summary>
        /// <param name="isVague">あいまい仕鳏蛟S可するか</param>
        /// ***********************************************************************
        public static void RemoveCache(string key, bool isVague = false)
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.Remove(key, isVague);
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// キャッシュを全破
        /// </summary>
        /// ***********************************************************************
        public static void RemoveCacheAll()
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.RemoveAll();
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 指定キ`のキャッシュS可する
        /// </summary>
        /// <param name="isVague">あいまい仕鳏蛟S可するか</param>
        /// ***********************************************************************
        public static void EnableCache(string key, bool isVague = false)
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.Enable(key, isVague);
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 全てのキャッシュS可する
        /// </summary>
        /// ***********************************************************************
        public static void EnableCacheAll()
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.EnableAll();
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 指定キ`のキャッシュS可しない
        /// </summary>
        /// <param name="isVague">あいまい仕鳏蛟S可するか</param>
        /// ***********************************************************************
        public static void DisableCache(string key, bool isVague = false)
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.Disable(key, isVague);
                }
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 全てのキャッシュS可しない
        /// </summary>
        /// ***********************************************************************
        public static void DisableCacheAll()
        {
            Scene scene = Current();
            if (scene != null)
            {
                CachePool cachePool = scene.CachePool;
                if (cachePool != null)
                {
                    cachePool.DisableAll();
                }
            }
        }

        #endregion

        #endregion

        //=========================================================================
        //. 初期化
        //=========================================================================
        #region 初期化

        // I理
        //  Awake()
        //  IEnumerator Start()
        //  {
        //      Preparation();
        //      
        //      while( m_Activate == false ) yield return null;
        //      
        //      while( OnStart() == false ) yield return null;
        //      
        //      Load();
        //      LoadPost();
        //
        //      Initialize();
        //  }

        /// ***********************************************************************
        /// <summary>
        /// 起rに呼ばれる
        /// </summary>
        /// ***********************************************************************
        protected virtual void Awake()
        {
            // 涫クリア
            m_Startup = false;

            // シ`ンまたぎでBGMを停止する
            m_BGMContinue = false;

            // リソ`スを全て破
            Resources.UnloadUnusedAssets();
            // ガベ`ジコレクト
            System.GC.Collect();

            // ビュ`コントロ`ラの取得
            m_ViewController = gameObject.FindChildComponentAll<ViewController>("view");
        }

        /// ***********************************************************************
        /// <summary>
        /// システム
        /// </summary>
        /// ***********************************************************************
        protected virtual IEnumerator Preparation()
        {
            // システムマネ`ジャの初期化
            while (SystemManager.Instance.isInitialized == false)
            {
                SystemManager.Instance.Initialize();
                yield return null;
            }

            // ゲ`ムマネ`ジャの初期化待ち
            while (GameManager.Instance.isInitialized == false)
            {
                GameManager.Instance.Initialize();
                yield return null;
            }

            // シ`ンマネ`ジャ取得
            m_SceneManager = GameManager.Instance.SceneManager;
        }

        /// ***********************************************************************
        /// <summary>
        /// ロ`ド
        /// </summary>
        /// ***********************************************************************
        protected virtual IEnumerator Load()
        {
            yield break;
        }
        protected virtual IEnumerator LoadPost()
        {
            yield break;
        }

        /// ***********************************************************************
        /// <summary>
        /// 更新前初期化
        /// </summary>
        /// ***********************************************************************
        protected virtual IEnumerator Start()
        {
            // システム
            yield return StartCoroutine(Preparation());

            // アクティベ`ト待ち
            while (m_Activate == false)
            {
                yield return null;
            }

            // シ`ン趣未ち
            while (OnStart() == false)
            {
                yield return null;
            }

            // ロ`ド
            yield return StartCoroutine(Load());
            yield return StartCoroutine(LoadPost());

            // 初期化
            Initialize();
        }

        /// ***********************************************************************
        /// <summary>
        /// シ`ンの_始v数
        /// </summary>
        /// ***********************************************************************
        protected virtual bool OnStart()
        {
            // キャッシュプ`ルの取得/生成
            m_CachePool = GetComponentInChildren<CachePool>();
            if (m_CachePool == null)
            {
                GameObject cachePool = new GameObject("cache_pool");
                cachePool.transform.SetParent(gameObject.transform, false);
                m_CachePool = cachePool.AddComponent<CachePool>();
            }

            // 初期化
            m_CachePool.Initialize();

            return true;
        }

        /// ***********************************************************************
        /// <summary>
        /// 初期化
        /// </summary>
        /// ***********************************************************************
        public override void Initialize()
        {
            if (isInitialized) return;

            // 基底の初期化
            base.Initialize();

            // ------------------------------------------------

            // ビュ`コントロ`ラ`初期化
            if (m_ViewController != null)
            {
                m_ViewController.Initialize();
            }

            // ステ`トO定
            m_State.Initialize();
            m_State.SetChangeCallback(StateChange);
            m_State.AddState("idle", StateIdle_Begin, StateIdle, StateIdle_End, StateLateIdle);
            m_State.AddState("setup", StateSetup_Begin, StateSetup, StateSetup_End, null);

            // 初期ステ`ト
            m_State.Reset("setup");
        }

        /// ***********************************************************************
        /// <summary>
        /// 破
        /// </summary>
        /// ***********************************************************************
        public override void Release()
        {
            // ビュ`コントロ`ラ`破
            if (m_ViewController != null)
            {
                m_ViewController.Release();
            }
            m_ViewController = null;

            // ビュ`が管理しているテキストを全破
            ViewManager.UnloadTextAll();

            // キャッシュ破
            if (m_CachePool != null)
            {
                m_CachePool.Release();
                m_CachePool = null;
            }

            // ------------------------------------------------

            // 基底の破
            base.Release();
        }

        #endregion

        //=========================================================================
        //. 更新
        //=========================================================================
        #region 更新

        /// ***********************************************************************
        /// <summary>
        /// 哎榨飑`ムコ`ルされる
        /// </summary>
        /// ***********************************************************************
        protected virtual void Update()
        {
            if (isInitialized == false)
            {
                return;
            }

            // あった方が良いがいまさら入れると危なそうなのでコメント
            // if( ErrorHandler.IsBusy( ) ) return;

            // スタ`トアップしている龊悉膝珐`ン切り替えがk生するとI理を更新しない
            if (IsStartup())
            {
                if (SceneManager.isBusy) return;
            }

#if UNITY_EDITOR
            if (FlowNode.EditorPauser != null)
            {
                FlowNode.EditorPauser.Activate();
            }
#endif

            // ステ`トマシン更新
            m_State.Update();

            // ビュ`コントロ`ラ`更新
            if (m_ViewController != null)
            {
                m_ViewController.Process();
            }
        }

        /// ***********************************************************************
        /// <summary>
        /// 哎榨飑`ムコ`ルされる(後I理)
        /// </summary>
        /// ***********************************************************************
        protected virtual void LateUpdate()
        {
            if (isInitialized == false)
            {
                return;
            }

            // あった方が良いがいまさら入れると危なそうなのでコメント
            // if( ErrorHandler.IsBusy( ) ) return;

            // スタ`トアップしている龊悉膝珐`ン切り替えがk生するとI理を更新しない
            if (IsStartup())
            {
                if (SceneManager.isBusy) return;
            }

            // ステ`トマシン更新
            m_State.LateUpdate();
        }

        #endregion

        //=========================================================================
        //. ビュ`
        //=========================================================================

        //=========================================================================
        //. O定/取得
        //=========================================================================
        #region O定/取得

        /// ***********************************************************************
        /// <summary>
        /// シ`ンアクティベ`ト
        /// </summary>
        /// ***********************************************************************
        public void Activate()
        {
            m_Activate = true;
        }

        /// ***********************************************************************
        /// <summary>
        /// スタ`トアップ
        /// </summary>
        /// ***********************************************************************
        protected void Startup()
        {
            m_Startup = true;
        }

        /// ***********************************************************************
        /// <summary>
        /// ステ`トリセット
        /// </summary>
        /// ***********************************************************************
        public void ResetState(string stateName, string nextState)
        {
            m_StateNext = nextState;
            m_State.Reset(stateName);
        }

        /// ***********************************************************************
        /// <summary>
        /// ステ`トリセット
        /// </summary>
        /// ***********************************************************************
        public void ResetState(string stateName)
        {
            m_StateNext = "";
            m_State.Reset(stateName);
        }

        /// ***********************************************************************
        /// <summary>
        /// ステ`トリクエスト
        /// </summary>
        /// ***********************************************************************
        public void RequestState(string stateName, string nextState)
        {
            m_StateNext = nextState;
            m_State.RequestState(stateName);
        }

        /// ***********************************************************************
        /// <summary>
        /// ステ`トリクエスト
        /// </summary>
        /// ***********************************************************************
        public void RequestState(string stateName)
        {
            m_StateNext = "";
            m_State.RequestState(stateName);
        }

        #endregion

        //=========================================================================
        //. _J
        //=========================================================================
        #region _J

        /// ***********************************************************************
        /// <summary>
        /// スタ`トアップチェック
        /// </summary>
        /// ***********************************************************************
        public bool IsStartup()
        {
            return m_Startup;
        }

        /// ***********************************************************************
        /// <summary>
        /// アイドルステ`トチェック
        /// </summary>
        /// ***********************************************************************
        public bool IsIdle()
        {
            if (m_State.EqualState("idle"))
            {
                return true;
            }
            return false;
        }

        /// ***********************************************************************
        /// <summary>
        /// セットアップステ`トチェック
        /// </summary>
        /// ***********************************************************************
        public bool IsSetup()
        {
            if (m_State.EqualState("setup"))
            {
                return true;
            }
            return false;
        }

        /// ***********************************************************************
        /// <summary>
        /// シ`ン涓中かチェック
        /// </summary>
        /// ***********************************************************************
        public bool IsSceneChange()
        {
            return false;
        }

        #endregion

        //=========================================================================
        //. イベント
        //=========================================================================
        #region イベント

        #endregion

        //=========================================================================
        //. ステ`ト
        //=========================================================================
        #region ステ`ト

        /// ***********************************************************************
        /// <summary>
        /// ステ`タス切り替えrに呼ばれる
        /// </summary>
        /// ***********************************************************************
        protected virtual void StateChange(StateMachine state)
        {
        }

        #endregion

        //=========================================================================
        //. アイドル
        //=========================================================================

        #region アイドル

        // _始
        protected virtual void StateIdle_Begin(StateMachine state)
        {
        }

        // メイン
        protected virtual void StateIdle(StateMachine state)
        {
        }
        // メイン(後)
        protected virtual void StateLateIdle(StateMachine state)
        {
        }

        // K了
        protected virtual void StateIdle_End(StateMachine state)
        {
        }

        #endregion

        //=========================================================================
        //. セットアップ
        //=========================================================================

        #region セットアップ

        // _始
        protected virtual void StateSetup_Begin(StateMachine state)
        {
        }

        // メイン
        protected virtual void StateSetup(StateMachine state)
        {
            if (m_ViewController == null)
            {
                RequestState("idle");
                return;
            }

            // ビュ`のI理を待つ
            if (m_ViewController.IsBusy() == false)
            {
                RequestState("idle");
            }
        }

        // K了
        protected virtual void StateSetup_End(StateMachine state)
        {
            // _始
            Startup();
        }

        #endregion
    }
}